
### login
POST localhost:8090/admin/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

### add token
POST localhost:8090/admin/add_token
Content-Type: application/json
Cookie: token={{admin_access_token}}

{
  "userid": 123456,
  "expire": 30
}


