
### login
POST localhost:8090/admin/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### add token
POST localhost:8090/admin/add_token
Content-Type: application/json
Cookie: token={{admin_access_token}}

{
  "userid": 123456,
  "expire": 30
}


### upload image
POST localhost:8090/admin/upload/image
Cookie: token={{admin_access_token}}
Content-Type: multipart/form-data; boundary=xxxxyyyyzzzz

--xxxxyyyyzzzz
Content-Disposition: form-data; name="file"; filename="test.png"

< /file/to/image/test.png
--xxxxyyyyzzzz--

###

