### hello
GET localhost:8090/hello/?name=John

### login
POST localhost:8090/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

### get image
GET localhost:8090/image/f4636813f0571a3fc035af92f61bcd0c


### upload image
POST localhost:8090/upload/image
Content-Type: multipart/form-data; boundary=xxxxyyyyzzzz

--xxxxyyyyzzzz
Content-Disposition: form-data; name="file"; filename="test.png"

< /file/to/image/test.png
--xxxxyyyyzzzz--

###

