
### login
POST localhost:8090/api/login
Content-Type: application/json

{
  "username": "bob",
  "password": "bob1234"
}

### hello
GET localhost:8090/api/hello
Authorization: Bearer {{access_token}}


### get image
GET localhost:8090/api/image/f4636813f0571a3fc035af92f61bcd0c
Authorization: Bearer {{access_token}}


### upload image
POST localhost:8090/api/upload/image
Authorization: Bearer {{access_token}}
Content-Type: multipart/form-data; boundary=xxxxyyyyzzzz

--xxxxyyyyzzzz
Content-Disposition: form-data; name="file"; filename="test.png"

< /file/to/image/test.png
--xxxxyyyyzzzz--

###

