
### login
POST localhost:8090/login
Content-Type: application/json

{
  "username": "abc",
  "password": "abc1234"
}

### hello
GET localhost:8090/api/hello?name=admin
Authorization: Bearer {{access_token}}


