server {
    listen              80;
    server_name         template.edtenz.cc;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Port $server_port;

    client_max_body_size 200M;

    location / {
        proxy_pass http://localhost:8090/;
        proxy_request_buffering off;
    }

    location /index.html {
        proxy_pass http://localhost:8090/;
    }

    location /login {
       proxy_pass http://localhost:8090/login;
    }

    location /logout {
       proxy_pass http://localhost:8090/logout;
    }

    location /static/ {
       proxy_pass http://localhost:8090/static/;
    }

    location /admin/ {
        proxy_pass http://localhost:8090/admin/;
    }

    location /api/ {
        proxy_pass http://localhost:8090/api/;
    }

    location /app/ {
        proxy_pass http://localhost:8090/app/;
    }

}
