// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package setup

import (
	"go-web-template/internal/config"
)

// Injectors from wire.go:

func InitializeControllers(cfg *config.Config) (*Controllers, error) {
	db, err := NewDatabase(cfg)
	if err != nil {
		return nil, err
	}
	user := NewUserRepository(db)
	jwtManager := NewJWTManager(cfg)
	apiServer := NewApiController(user, jwtManager)
	serviceUser := NewUserService(cfg, user)
	adminServer := NewAdminController(serviceUser, jwtManager)
	authServer := NewAuthController(user, serviceUser, jwtManager)
	userServer := NewUserController(serviceUser, jwtManager)
	webServer := NewWebController(cfg, apiServer, adminServer, authServer, userServer, jwtManager)
	controllers := NewControllers(webServer)
	return controllers, nil
}
