// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package setup

import (
	"go-web-template/internal/config"
	"go-web-template/internal/controller"
	"go-web-template/internal/repository"
	"go-web-template/internal/service"
)

// Injectors from wire.go:

func InitializeControllers(configConfig *config.Config) (*Controllers, error) {
	user := repository.NewUser()
	serviceUser := service.NewUser(configConfig, user)
	apiServer := controller.NewApiServer(serviceUser)
	adminServer := controller.NewAdminServer(serviceUser)
	webServer := controller.NewWebServer(configConfig, apiServer, adminServer)
	controllers := &Controllers{
		webServer: webServer,
	}
	return controllers, nil
}
