verbose: true
env: "local"
app:
  name: "go-web-template"
  port: 8088
  web: "./web"
  debug: true
  log_level: "debug"
  log_file: "./log/app.log"
db:
  path: "./data/app.db"
  debug: false
  max_open_conns: 100
  max_idle_conns: 10
  conn_max_lifetime: "1h"
jwt:
  secret: "${JWT_SECRET}"
  expire_time: "24h"
  issuer: "go-web-template"

