verbose: true
env: "local"
app:
  name: "go-web-template"
  port: 8081
  web: "./web"
  secret: "${APP_SECRET}"
db:
  host: "localhost"
  port: 3306
  user: "root"
  pass: "${DB_PASS}"
  db: "mytest_db"

