verbose: true
env: "local"
app:
  name: "go-web-template"
  port: 8088
  web: "./web"
  debug: true
  log_level: "debug"
  log_file: "./log/app.log"
db:
  path: "./data/app.db"
  debug: false
jwt:
  secret: "${JWT_SECRET}"
  expire_time: "15m"
  issuer: "go-web-template"

