// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package constant

import (
	"errors"
	"fmt"
)

const (
	// RoleUser is a Role of type User.
	RoleUser Role = iota
	// RoleAdmin is a Role of type Admin.
	RoleAdmin
)

var ErrInvalidRole = errors.New("not a valid Role")

const _RoleName = "useradmin"

var _RoleMap = map[Role]string{
	RoleUser:  _RoleName[0:4],
	RoleAdmin: _RoleName[4:9],
}

// String implements the Stringer interface.
func (x Role) String() string {
	if str, ok := _RoleMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Role(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Role) IsValid() bool {
	_, ok := _RoleMap[x]
	return ok
}

var _RoleValue = map[string]Role{
	_RoleName[0:4]: RoleUser,
	_RoleName[4:9]: RoleAdmin,
}

// ParseRole attempts to convert a string to a Role.
func ParseRole(name string) (Role, error) {
	if x, ok := _RoleValue[name]; ok {
		return x, nil
	}
	return Role(0), fmt.Errorf("%s is %w", name, ErrInvalidRole)
}

// MarshalText implements the text marshaller method.
func (x Role) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Role) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseRole(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Role) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
